name = "MechanismGeometries"
uuid = "931e9471-e8fb-5385-a477-07ad12718aca"
version = "0.4.1"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorTypes = "≥ 0.2.0"
CoordinateTransformations = "≥ 0.4.1"
GeometryTypes = "≥ 0.4.0"
LightXML = "≥ 0.4.0"
RigidBodyDynamics = "≥ 2.0.0"
Rotations = "≥ 0.6.1"
StaticArrays = "≥ 0.5.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ValkyrieRobot = "c74b26e8-f247-5d24-b013-c11a2bbd97c6"

[targets]
test = ["ValkyrieRobot", "Test"]
